name: Docker Image

concurrency:
  group: workflow_staging_environment
  cancel-in-progress: true

on:
    push:
        branches: [ "main", "feature/dockerfile" ]

jobs:

    push_image:
        runs-on: ubuntu-latest
        concurrency:
          group: job_staging_environment
          cancel-in-progress: true
        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  custom-boolean: true
                  custom-string: "Hello World"

            - name: Build and push Docker image
              uses: docker/build-push-action@v2.10.0
              with:
                  context: .
                  push: true
                  tags: ghcr.io/mhprodev/mhddos:${{ github.sha }},ghcr.io/mhprodev/mhddos:latest
