package io.github.typesafegithub.workflows.dsl.expressions.contexts

import io.github.typesafegithub.workflows.dsl.expressions.ExpressionContext

/**
 * The github context contains information about the workflow run and the event that triggered the run.
 * You can also read most of the github context data in environment variables.
 * For more information about environment variables,
 * https://docs.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
 *
 * See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
 * **/
public object GitHubContext : ExpressionContext("github") {
    /**
     * Types generated by the test GenerateEventPayloadTest
     *
     * We read event payloads from github-workflows-kt/src/test/resources/payloads
     * We generate it inside       github-workflows-kt/src/gen/kotlin/io/github/typesafegithub/workflows/expr
     *
     * The JSONs come from https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
     * Feel free to add any payload you might need from that page
     * */

    public val eventWorkflowDispatch: WorkflowDispatchEvent = WorkflowDispatchEvent

    public val eventRelease: ReleaseEvent = ReleaseEvent

    public val eventPullRequest: PullRequestEvent = PullRequestEvent

    public val eventPush: PushEvent = PushEvent

/** Standard properties **/
    public val token: String by propertyToExprPath

    public val job: String by propertyToExprPath

    public val ref: String by propertyToExprPath

    public val sha: String by propertyToExprPath

    public val repository: String by propertyToExprPath

    public val repository_owner: String by propertyToExprPath

    public val repositoryUrl: String by propertyToExprPath

    public val run_id: String by propertyToExprPath

    public val run_number: String by propertyToExprPath

    public val retention_days: String by propertyToExprPath

    public val run_attempt: String by propertyToExprPath

    public val actor: String by propertyToExprPath

    public val workflow: String by propertyToExprPath

    public val head_ref: String by propertyToExprPath

    public val base_ref: String by propertyToExprPath

    public val event_name: String by propertyToExprPath

    public val server_url: String by propertyToExprPath

    public val api_url: String by propertyToExprPath

    public val graphql_url: String by propertyToExprPath

    public val ref_name: String by propertyToExprPath

    public val ref_protected: String by propertyToExprPath

    public val ref_type: String by propertyToExprPath

    public val secret_source: String by propertyToExprPath

    public val workspace: String by propertyToExprPath

    public val action: String by propertyToExprPath

    public val event_path: String by propertyToExprPath

    public val action_repository: String by propertyToExprPath

    public val action_ref: String by propertyToExprPath

    public val path: String by propertyToExprPath

    public val env: String by propertyToExprPath

    public val actor_id: String by propertyToExprPath

    public val artifact_cache_size_limit: String by propertyToExprPath

    public val repository_id: String by propertyToExprPath

    public val repository_owner_id: String by propertyToExprPath

    public val step_summary: String by propertyToExprPath
}
